-- ═══════════════════════════════════════════════════════════════════════
-- SamKass Subscription Enforcement System - Database Schema
-- ═══════════════════════════════════════════════════════════════════════
-- 
-- CRITICAL RULES:
-- - All timestamps are UTC (ISO 8601 format: "2025-01-15T10:30:00Z")
-- - expiry_time is the single source of truth for subscription validity
-- - One active subscription per user (email-based)
-- - Payment verification is server-side only
--
-- USAGE:
-- 1. Run this SQL on your Supabase database
-- 2. The SubscriptionManager will handle all subscription operations
-- 3. Frontend calls /api/subscription/* endpoints for status checks
--

-- ─────────────────────────────────────────────────────────────────────
-- SUBSCRIPTIONS TABLE
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL UNIQUE,
  plan_type TEXT NOT NULL CHECK (plan_type IN ('free', 'oneday', 'monthly', 'quarterly', 'yearly')),
  plan_name TEXT NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  expiry_time TIMESTAMP WITH TIME ZONE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired', 'cancelled')),
  payment_id TEXT,
  razorpay_order_id TEXT,
  razorpay_signature TEXT,
  amount_paid DECIMAL(10, 2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────
-- INDEXES FOR PERFORMANCE
-- ─────────────────────────────────────────────────────────────────────
CREATE INDEX idx_subscriptions_email ON subscriptions(email);
CREATE INDEX idx_subscriptions_expiry_time ON subscriptions(expiry_time);
CREATE INDEX idx_subscriptions_status ON subscriptions(status);
CREATE INDEX idx_subscriptions_plan_type ON subscriptions(plan_type);

-- ─────────────────────────────────────────────────────────────────────
-- PAYMENT HISTORY TABLE (for auditing and reporting)
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payment_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT NOT NULL,
  subscription_id BIGINT REFERENCES subscriptions(id),
  plan_type TEXT NOT NULL,
  amount_paid DECIMAL(10, 2) NOT NULL,
  payment_id TEXT,
  razorpay_order_id TEXT,
  razorpay_signature TEXT,
  status TEXT NOT NULL DEFAULT 'success' CHECK (status IN ('success', 'failed', 'pending')),
  payment_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_payment_history_email ON payment_history(email);
CREATE INDEX idx_payment_history_payment_date ON payment_history(payment_date);
CREATE INDEX idx_payment_history_subscription_id ON payment_history(subscription_id);

-- ─────────────────────────────────────────────────────────────────────
-- FUNCTION: Update subscription status on expiry check
-- ─────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_subscription_status()
RETURNS TRIGGER AS $$
BEGIN
  -- Automatically mark as 'expired' if expiry_time has passed
  IF NEW.expiry_time IS NOT NULL AND NEW.expiry_time <= now() THEN
    NEW.status = 'expired';
  END IF;
  
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_subscription_status
BEFORE INSERT OR UPDATE ON subscriptions
FOR EACH ROW EXECUTE FUNCTION update_subscription_status();

-- ─────────────────────────────────────────────────────────────────────
-- RLS (ROW LEVEL SECURITY) POLICIES
-- ─────────────────────────────────────────────────────────────────────
-- Enable RLS for subscriptions table
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- Policy: Allow service role (backend) full access
CREATE POLICY subscriptions_service_role_access
  ON subscriptions
  USING (true)
  WITH CHECK (true)
  FOR ALL
  TO service_role;

-- Policy: Allow authenticated users to read only their own subscription
CREATE POLICY subscriptions_user_read
  ON subscriptions
  USING (email = current_user_id())
  FOR SELECT;

-- Note: Updates/deletes are only done via backend API, not directly from frontend

-- ─────────────────────────────────────────────────────────────────────
-- SEED DATA (OPTIONAL - for testing)
-- ─────────────────────────────────────────────────────────────────────
-- Uncomment to create a test free tier subscription:
-- INSERT INTO subscriptions (email, plan_type, plan_name, status)
-- VALUES ('test@example.com', 'free', 'Free Plan', 'active')
-- ON CONFLICT (email) DO NOTHING;
