/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SimpleResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'staff' : IDL.Null });
export const UserProfile = IDL.Record({
  'financierName' : IDL.Text,
  'role' : UserRole,
  'businessName' : IDL.Text,
  'phone' : IDL.Text,
});
export const AuthResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'changePin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [SimpleResult], []),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'phoneExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, UserRole],
      [SimpleResult],
      [],
    ),
  'resetPin' : IDL.Func([IDL.Text, IDL.Text], [SimpleResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SimpleResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'staff' : IDL.Null });
  const UserProfile = IDL.Record({
    'financierName' : IDL.Text,
    'role' : UserRole,
    'businessName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AuthResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  
  return IDL.Service({
    'changePin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [SimpleResult], []),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'phoneExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, UserRole],
        [SimpleResult],
        [],
      ),
    'resetPin' : IDL.Func([IDL.Text, IDL.Text], [SimpleResult], []),
  });
};

export const init = ({ IDL }) => { return []; };