/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthResult = { 'ok' : UserProfile } |
  { 'err' : string };
export type SimpleResult = { 'ok' : null } |
  { 'err' : string };
export interface UserProfile {
  'financierName' : string,
  'role' : UserRole,
  'businessName' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'staff' : null };
export interface _SERVICE {
  'changePin' : ActorMethod<[string, string, string], SimpleResult>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'login' : ActorMethod<[string, string], AuthResult>,
  'phoneExists' : ActorMethod<[string], boolean>,
  'register' : ActorMethod<
    [string, string, string, string, UserRole],
    SimpleResult
  >,
  'resetPin' : ActorMethod<[string, string], SimpleResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];