/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SimpleResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type AuthResult = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface UserProfile {
    financierName: string;
    role: UserRole;
    businessName: string;
    phone: string;
}
export enum UserRole {
    admin = "admin",
    staff = "staff"
}
export interface backendInterface {
    changePin(phone: string, currentHashedPin: string, newHashedPin: string): Promise<SimpleResult>;
    getUserProfile(phone: string): Promise<UserProfile | null>;
    login(phone: string, hashedPin: string): Promise<AuthResult>;
    phoneExists(phone: string): Promise<boolean>;
    register(phone: string, hashedPin: string, financierName: string, businessName: string, role: UserRole): Promise<SimpleResult>;
    resetPin(phone: string, newHashedPin: string): Promise<SimpleResult>;
}
import type { AuthResult as _AuthResult, SimpleResult as _SimpleResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async changePin(arg0: string, arg1: string, arg2: string): Promise<SimpleResult> {
        if (this.processError) {
            try {
                const result = await this.actor.changePin(arg0, arg1, arg2);
                return from_candid_SimpleResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePin(arg0, arg1, arg2);
            return from_candid_SimpleResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_AuthResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_AuthResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async phoneExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.phoneExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.phoneExists(arg0);
            return result;
        }
    }
    async register(arg0: string, arg1: string, arg2: string, arg3: string, arg4: UserRole): Promise<SimpleResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2, arg3, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg4));
                return from_candid_SimpleResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2, arg3, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg4));
            return from_candid_SimpleResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPin(arg0: string, arg1: string): Promise<SimpleResult> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPin(arg0, arg1);
                return from_candid_SimpleResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPin(arg0, arg1);
            return from_candid_SimpleResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SimpleResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SimpleResult): SimpleResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    financierName: string;
    role: _UserRole;
    businessName: string;
    phone: string;
}): {
    financierName: string;
    role: UserRole;
    businessName: string;
    phone: string;
} {
    return {
        financierName: value.financierName,
        role: from_candid_UserRole_n6(_uploadFile, _downloadFile, value.role),
        businessName: value.businessName,
        phone: value.phone
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    staff: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "staff" in value ? UserRole.staff : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n4(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    staff: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.staff ? {
        staff: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
